//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patikapp_proj_2.Modells
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_base_controll_variables
    {
        public int id { get; set; }
        public bool use_database_external { get; set; }
        public int numDays_for_debt_expiration_PhTpPh { get; set; }
        public int numDays_for_debt_expiration_PhToPa { get; set; }
    }
}
