//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patikapp_proj_2.Modells
{
    using System;
    using System.Collections.Generic;
    
    public partial class gyogysz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gyogysz()
        {
            this.debtphtoph = new HashSet<debtphtoph>();
        }
    
        public int OEP_TTT { get; set; }
        public string OEP_NEV { get; set; }
        public string OEP_KSZ { get; set; }
        public string GYFORMA { get; set; }
        public string KISZ_MENNY { get; set; }
        public string KISZ_EGYS { get; set; }
        public string BRANDNEV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<debtphtoph> debtphtoph { get; set; }
    }
}
