//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patikapp_proj_2.Modells
{
    using System;
    using System.Collections.Generic;
    
    public partial class messagestoph
    {
        public int id { get; set; }
        public int owner_id { get; set; }
        public string message { get; set; }
        public byte[] photo { get; set; }
    
        public virtual pharmacies pharmacies { get; set; }
    }
}
