//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patikapp_proj_2.Modells
{
    using System;
    using System.Collections.Generic;
    
    public partial class pharmacies_data
    {
        public int id { get; set; }
        public int pharmacy_id { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string facebook { get; set; }
        public string adress { get; set; }
    }
}
