//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patikapp_proj_2.Modells
{
    using System;
    using System.Collections.Generic;
    
    public partial class todolist
    {
        public int id { get; set; }
        public int actor_id { get; set; }
        public int pharmacy_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DeadLine { get; set; }
        public bool IsReady { get; set; }
    }
}
