//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Patikapp_proj_2.Modells
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vpharmacies_databaseEntities : DbContext
    {
        public vpharmacies_databaseEntities()
            : base("name=vpharmacies_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<application_base_controll_variables> application_base_controll_variables { get; set; }
        public virtual DbSet<debtphtopa> debtphtopa { get; set; }
        public virtual DbSet<debtphtoph> debtphtoph { get; set; }
        public virtual DbSet<gyogysz> gyogysz { get; set; }
        public virtual DbSet<message_to_patient> message_to_patient { get; set; }
        public virtual DbSet<messagestoph> messagestoph { get; set; }
        public virtual DbSet<pharmacies> pharmacies { get; set; }
        public virtual DbSet<pharmacies_data> pharmacies_data { get; set; }
        public virtual DbSet<psw> psw { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<todolist> todolist { get; set; }
        public virtual DbSet<user_roles> user_roles { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_data> users_data { get; set; }
        public virtual DbSet<todo> todo { get; set; }
    }
}
